# action.yml
name: 'THREDDS Test Action'
description: 'An action to run tests for the various THREDDS projects'
inputs:
  java-version:  # id of input
    description: 'Version of java to use when running the tests'
    required: false
    default: '11'
  test-command:  # id of input
    description: 'Command used to run the tests'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.java-version }}
    - ${{ inputs.test-command }}

