on: [push]

jobs:
  thredds-test-job:
    runs-on: ubuntu-latest
    name: Run test
    steps:
    - name: test
      id: test
      uses: lesserwhirls/thredds-test-action@main
      with:
        java-version: 8
        test-command: "java -version"

